describe("databricks.config", function()
  local config

  before_each(function()
    -- Clear module cache for a fresh load each time
    package.loaded["databricks.config"] = nil
    config = require("databricks.config")
  end)

  describe("validate_cluster_id", function()
    it("accepts valid cluster IDs", function()
      assert.is_true(config.validate_cluster_id("0123-456789-abcde123"))
      assert.is_true(config.validate_cluster_id("1234-567890-xyz12345"))
    end)

    it("rejects empty or nil", function()
      assert.is_false(config.validate_cluster_id(""))
      assert.is_false(config.validate_cluster_id(nil))
    end)

    it("rejects invalid formats", function()
      assert.is_false(config.validate_cluster_id("not-a-cluster-id"))
      assert.is_false(config.validate_cluster_id("0123_456789_abc"))
      assert.is_false(config.validate_cluster_id("0123-456789"))
      assert.is_false(config.validate_cluster_id("abc-def-ghi"))
    end)

    it("rejects injection attempts", function()
      assert.is_false(config.validate_cluster_id("0123-456789-abc; rm -rf /"))
      assert.is_false(config.validate_cluster_id("0123-456789-abc$(whoami)"))
      assert.is_false(config.validate_cluster_id("0123-456789-abc`id`"))
    end)

    it("rejects non-string types", function()
      assert.is_false(config.validate_cluster_id(12345))
      assert.is_false(config.validate_cluster_id(true))
      assert.is_false(config.validate_cluster_id({}))
    end)
  end)

  describe("validate_dbfs_path", function()
    it("accepts valid DBFS paths", function()
      assert.is_true(config.validate_dbfs_path("dbfs:/tmp/databricks-nvim"))
      assert.is_true(config.validate_dbfs_path("dbfs:/mnt/data/file.py"))
    end)

    it("rejects non-dbfs paths", function()
      assert.is_false(config.validate_dbfs_path("/tmp/local"))
      assert.is_false(config.validate_dbfs_path("s3://bucket/key"))
    end)

    it("rejects path traversal", function()
      assert.is_false(config.validate_dbfs_path("dbfs:/tmp/../etc/passwd"))
      assert.is_false(config.validate_dbfs_path("dbfs:/tmp/.."))
    end)

    it("rejects shell metacharacters", function()
      assert.is_false(config.validate_dbfs_path("dbfs:/tmp/foo;rm -rf /"))
      assert.is_false(config.validate_dbfs_path("dbfs:/tmp/foo|cat /etc/passwd"))
      assert.is_false(config.validate_dbfs_path("dbfs:/tmp/foo$(whoami)"))
      assert.is_false(config.validate_dbfs_path("dbfs:/tmp/foo`id`"))
      assert.is_false(config.validate_dbfs_path("dbfs:/tmp/foo&bg"))
    end)

    it("rejects empty or nil", function()
      assert.is_false(config.validate_dbfs_path(""))
      assert.is_false(config.validate_dbfs_path(nil))
    end)
  end)

  describe("validate_local_path", function()
    it("rejects non-.py files", function()
      assert.is_false(config.validate_local_path("/tmp/script.sh"))
      assert.is_false(config.validate_local_path("/tmp/data.csv"))
    end)

    it("rejects path traversal", function()
      assert.is_false(config.validate_local_path("/tmp/../etc/passwd.py"))
    end)

    it("rejects empty or nil", function()
      assert.is_false(config.validate_local_path(""))
      assert.is_false(config.validate_local_path(nil))
    end)

    it("rejects non-string types", function()
      assert.is_false(config.validate_local_path(123))
      assert.is_false(config.validate_local_path(true))
    end)
  end)

  describe("validate_profile", function()
    it("accepts valid profile names", function()
      assert.is_true(config.validate_profile("DEFAULT"))
      assert.is_true(config.validate_profile("my-workspace"))
      assert.is_true(config.validate_profile("prod_env"))
      assert.is_true(config.validate_profile("dev123"))
    end)

    it("rejects shell injection in profile names", function()
      assert.is_false(config.validate_profile("DEFAULT; rm -rf /"))
      assert.is_false(config.validate_profile("foo bar"))
      assert.is_false(config.validate_profile("$(whoami)"))
      assert.is_false(config.validate_profile("foo`id`"))
    end)

    it("rejects empty or nil", function()
      assert.is_false(config.validate_profile(""))
      assert.is_false(config.validate_profile(nil))
    end)
  end)

  describe("setup", function()
    it("uses defaults when called without opts", function()
      config.setup()
      local cfg = config.get()
      assert.equals("DEFAULT", cfg.profile)
      assert.equals("dbfs:/tmp/databricks-nvim", cfg.upload_path)
      assert.equals(5000, cfg.poll_interval_ms)
      assert.is_nil(cfg.cluster_id)
    end)

    it("merges user options with defaults", function()
      config.setup({ profile = "staging", output_height = 20 })
      local cfg = config.get()
      assert.equals("staging", cfg.profile)
      assert.equals(20, cfg.output_height)
      assert.equals("dbfs:/tmp/databricks-nvim", cfg.upload_path)
    end)

    it("resets invalid cluster_id to nil", function()
      config.setup({ cluster_id = "INVALID" })
      local cfg = config.get()
      assert.is_nil(cfg.cluster_id)
    end)

    it("resets invalid upload_path to default", function()
      config.setup({ upload_path = "/local/path" })
      local cfg = config.get()
      assert.equals("dbfs:/tmp/databricks-nvim", cfg.upload_path)
    end)

    it("resets invalid profile to DEFAULT", function()
      config.setup({ profile = "bad profile!" })
      local cfg = config.get()
      assert.equals("DEFAULT", cfg.profile)
    end)

    it("accepts valid cluster_id", function()
      config.setup({ cluster_id = "0123-456789-abcde123" })
      local cfg = config.get()
      assert.equals("0123-456789-abcde123", cfg.cluster_id)
    end)
  end)
end)
